# This is a basic workflow to help you get started with Actions

name: QT

# Controls when the workflow will run
on:
    push:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.github/workflows/windows.yml'
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Runtime
        run: sudo apt install -y clang-format clang-tidy clang-tools clang clangd libc++-dev libc++abi-dev libc++abi1 libclang-dev libclang1 libllvm-ocaml-dev libomp-dev libomp5 lld lldb llvm-dev llvm-runtime llvm python-clang
      - name: Qt xcb opengl
        run: sudo apt install -y libgl-dev libglu-dev    libfontconfig1-dev  libfreetype6-dev  libx11-dev  libx11-xcb-dev  libxext-dev  libxfixes-dev    libxi-dev    libxrender-dev    libxcb1-dev    libxcb-glx0-dev    libxcb-keysyms1-dev    libxcb-image0-dev    libxcb-shm0-dev    libxcb-icccm4-dev    libxcb-sync-dev    libxcb-xfixes0-dev    libxcb-shape0-dev    libxcb-randr0-dev    libxcb-render-util0-dev    libxcb-util-dev    libxcb-xinerama0-dev    libxcb-xkb-dev    libxkbcommon-dev    libxkbcommon-x11-dev
      - name: Install QT Src
        run: wget -q https://download.qt.io/official_releases/qt/6.4/6.4.2/single/qt-everywhere-src-6.4.2.tar.xz
      - run: tar -xf qt-everywhere-src-6.4.2.tar.xz
      - name: Build
        run: |
          ls -all 
          cd qt-everywhere-src-6.4.2
          ./configure --help
          ./configure -prefix ./static-build -release -confirm-license -opensource -c++std c++11 -static  -no-qml-debug -platform linux-g++-64  -qt-zlib -qt-libpng -qt-libjpeg -no-journald  -openssl -opengl -xcb -skip qtquickcontrols -skip qtquickcontrols2 -skip qtsensors -skip qtdoc -skip examples
          make
          make install
